packages:
  - '.'
  - 'electron'

allowBuilds:
  electron: true
  electron-click-drag-plugin: true
  esbuild: true
  vue-demi: true

onlyBuiltDependencies:
  - electron
  - electron-click-drag-plugin
  - esbuild
  - vue-demi
